### ISSUE TITLE
getPrimaryGroup(player) - not really primary. (bPerms)

### ISSUE THREAD

**Issue by atajsic** [MilkBowl/Vault#206]
Long story short, if a user has groups 

```
users:
  Tazzernator:
    permissions: []
    groups:
    - guest
    - knight
```

Vault's getPrimaryGroup(player) returns guest, as it is position 0.

Perhaps one could use the priority value, and compare the groups and return the group with the highest priority?

Thanks,
Andrew
