### ISSUE TITLE
Failed to import from vault, does not exist?!

### ISSUE THREAD

**Issue by Lightning11wins** [MilkBowl/Vault#736]
I downloaded the JAR and placed it in my server's plugin folder, but when I went to implement it, all the imports could not be found. My compiler says "package net.milkbowl.vault.chat does not exist"! Am I suposed to use a vault library or something?

**Comment by Sleaker** [comment]
sounds like you are having issues setting up your IDE properly.

**Comment by Lightning11wins** [comment]
Am I suposed to do more than just drop the JAR in my plugins folder?

**Comment by Lightning11wins** [comment]
By the way... this is my current plugin.yml. Am I doing it right?

```
name: MageCraft

author: Lightning_11 (Owner)

main: com.javaminecraft.CasterMain

commands:
    Target:
        description: (Unused) Set your next spell's target
        usage: /Target <Player>
    Spell:
        description: Cast a spell
        usage: /Spell [SpellLevel/Highest]
    Tome:
        description: Help on magic
        usage: /Tomb [Info Type]
    Dimentions:
        description: Tests to see if the world dimention variables are set
        usage: /Dimentions
    Shop:
        description: Open an NPC shop for the closest player
        usage: /Shop <Shop Name> <x> <y> <z>
    Test:
        description: Used by staff to test new features
        usage: /Test

depend: plugins.Vault

version: Alfa 23
```
